FROM ubuntu:latest

RUN apt clean && apt update && apt update -y

# 検証用ツール
RUN apt install -y vim \
        # ping command
        iputils-ping \
        # ip command
        iproute2 \
        # traceroute command
        traceroute \
        # ネットワークパケットをキャプチャして表示するためのユーティリティ
        tcpdump \
        # firewall
        ufw

RUN apt install -y  netfilter-persistent \
                    systemctl

RUN sed -i 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/' /etc/sysctl.conf && \
    sysctl -p

# 正常に実行したが変わらず
#RUN iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT && \
#    iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT && \
#    /etc/init.d/netfilter-persistent restart

# 手動で実行したが変わらず
#RUN iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT && \
#    iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT && \
#   iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -o eth1 -j MASQUERADE && \
#   iptables -A FORWARD -s 192.168.1.0/24 -d 192.168.2.0/24 -p icmp --icmp-type echo-request -j ACCEPT
#    /etc/init.d/netfilter-persistent restart