FROM debian:bookworm-slim

RUN apt clean && apt update && apt upgrade -y

# 検証用ツール
RUN apt install -y vim \
        # ping command
        iputils-ping \
        # ip command
        iproute2 \
        # traceroute command
        traceroute \
        # wiresharkのコマンドライン版
        tshark

COPY ./init.sh /home/init.sh
RUN chmod +x /home/init.sh

CMD ["/home/init.sh"]