version: "3.9"

services:
  router0:
    container_name: router0
    build: ./router
    privileged: true
    tty: true
    volumes:
      - ./init.sh:/home/init.sh
    command: /home/init.sh router &
    #/proc/sys/net/ipv4/ip_forwardの設定変更
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      network0:
        ipv4_address: 10.0.0.2
      network1:
        ipv4_address: 10.0.1.2
      network2:
        ipv4_address: 10.0.2.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          memory: 512M

  router1:
    container_name: router1
    build: ./router
    privileged: true
    tty: true
    volumes:
      - ./init.sh:/home/init.sh
    command: /home/init.sh router &
    #/proc/sys/net/ipv4/ip_forwardの設定変更
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      network1:
        ipv4_address: 10.0.1.3
      network3:
        ipv4_address: 10.0.3.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          memory: 512M

  router2:
    container_name: router2
    build: ./router
    privileged: true
    tty: true
    volumes:
      - ./init.sh:/home/init.sh
    command: /home/init.sh router &
    #/proc/sys/net/ipv4/ip_forwardの設定変更
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      network2:
        ipv4_address: 10.0.2.3
      network4:
        ipv4_address: 10.0.4.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          memory: 512M

  router3:
    container_name: router3
    build: ./router
    privileged: true
    tty: true
    volumes:
      - ./init.sh:/home/init.sh
    command: /home/init.sh router &
    #/proc/sys/net/ipv4/ip_forwardの設定変更
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      network3:
        ipv4_address: 10.0.3.3
      network4:
        ipv4_address: 10.0.4.3
      network5:
        ipv4_address: 10.0.5.2
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          memory: 512M

  host0:
    container_name: host0
    build: .
    privileged: true
    tty: true
    volumes:
      - ./init.sh:/home/init.sh
    # デフォルトゲートウェイの設定
    command: /home/init.sh host 10.0.0.2 &
    networks:
      #  network0がeth0に割り当てられる
      network0:
        ipv4_address: 10.0.0.10
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          memory: 512M

  host1:
    container_name: host1
    build: .
    privileged: true
    tty: true
    volumes:
      - ./init.sh:/home/init.sh
    # デフォルトゲートウェイの設定
    command: /home/init.sh host 10.0.5.2 &
    networks:
      #  network3がeth0に割り当てられる
      network3:
        ipv4_address: 10.0.5.10
    deploy:
      resources:
        limits:
          cpus: "1.0"
        reservations:
          memory: 512M

networks:
  network0:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

  network1:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

  network2:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24

  network3:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24

  network4:
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24

  network5:
    ipam:
      driver: default
      config:
        - subnet: 10.0.5.0/24
