FROM debian:bookworm-slim

RUN apt clean && apt update && apt upgrade -y

# よく使うツール
RUN apt install -y \
        # psコマンド
        procps

# ソースのインストール用ツール
RUN apt install -y \
        # Linux Standard Base（LSB）のバージョン情報を提供するためのツールらしい
        lsb-release \
        gnupg \
        curl

# ここから公式のFrrインストールするコマンド
RUN curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null

ENV FRRVER="frr-stable"

RUN echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr \
     $(lsb_release -s -c) $FRRVER | tee -a /etc/apt/sources.list.d/frr.list

RUN apt update && apt install -y frr frr-pythontools
# ここまで

COPY ./init.sh /home/init.sh
RUN chmod +x /home/init.sh

CMD ["/home/init.sh"]